MarkSchofield/WindowsToolchain

Support/MidlRT.cmake, example/RuntimeComponent/CMakeLists.txt
This PR addresses #6: Rather than overriding `add_library` - which turns out to be a bit dangerous - an explicit call to `enable_midlrt(<target>)` is necessary to add MidlRT support.
=> Require 'enable_midlrt'; CMake function overriding only works once

example/nuget.config
Without a `nuget.config` the build is dependent on user configuration. By adding a `nuget.config` to the root of the build, the configuration is contained in the source.
=> Add 'nuget.config' to avoid external dependencies

NuGet.cmake
NuGet.cmake doesn't check the return code from running nuget - capture the error result and output, and report a FATAL_ERROR on failure.
=> Report nuget.exe errors to CMake

Ninja.cmake, ToolchainCommon.cmake, Windows.Clang.toolchain.cmake, Windows.MSVC.toolchain.cmake, example/CMakePresets.json, example/README.md, example/initialize.ps1
CMake doesn't need the 'CMAKE_MAKE_PROGRAM' to be available until it encounters a 'project' node. Which means that a Toolchain can download the CMAKE_MAKE_PROGRAM to minimize the 'pre-CMake' build steps. This PR adds support to download (for Windows only at the minute!) Ninja if a Ninja generator is being used. The script needs to be told where to download to - by setting the 'TOOLCHAIN_TOOLS_PATH' variable - and if the variable isn't set, then minimal work is performed.
=> Download Ninja from within the CMake build as necessary

Windows.MSVC.toolchain.cmake, example/CMakePresets.json
Adding support for Spectre mitigations. Since Spectre mitigations need a compiler option **_and_** a custom link path, adding support in the toolchain seems reasonable. TBH, adding better defaults for security mitigations (i.e. `/guard:cf`, `/sdl`, `/CETCOMPAT` and a higher warning level) would probably be a good idea. Thoughts?
This addresses #13.
----
I switched to just controlling the use of the runtime with Spectre mitigations enabled - which seems to be more appropriate for the toolchain. Setting VS_USE_SPECTRE_MITIGATION_RUNTIME to be on/true will cause the toolchain to link with the runtime with Spectre mitigations. It defaults to OFF. This means that the mitigations (and associated performance affects) are off by default, and the expectation would be that if the runtime is being …
=> Add support for Spectre mitigations

Support/Midl.cmake, Support/MidlRT.cmake
When compiling a CMake project with a Visual Studio Generator, certain functionality is picked up from the built-in props/targets that are included by default by the generated project. To allow other generators to support that functionality, the support needs to be described on the "CMake-side", not the "Generator-build-side". And this PR adds a simple description of "non-WinRT MIDL" to the CMake-side. There's _some_ overlap with `MidlRT.cmake`, but enough differences that I've kept the support separate. I need to add an example, but I've been using this myself for a while that sending it out for general awareness seems reasonable
=> Add support for non-WinRT Midl

.github/workflows/ci.yaml
In order to try out different workflows in a topic branch, there needs to be a workflow YAML file in the 'default' (i.e. main) branch. So this PR adds a simple, trivial workflow - it simply checks-out the repo.
=> Add a trivial workflow

.github/CODEOWNERS, .github/workflows/ci.yaml, README.md, example/CMakePresets.json, example/build.ps1
This PR addresses #21 and #22, and also adds a `.github/CODEOWNERS` file.
The `ci.yaml` specifies a GitHub Workflow that builds {Debug, Release} x { windows-msvc-x64, windows-msvc-x86, windows-msvc-arm64, windows-clang-x64 }. It simply checks-outs the repo, configures and builds the 'examples' folder and uploads the contents of the `CMAKE_BINARY_DIR` as an artifact (to capture logs for debugging as well as output). CMake errors break the build. The Artifact excludes intermediate files that aren't particularly useful, just to be thrifty with artifact upload/download.
=> Add a PR/CI workflow that builds the 'examples' folder

Support/CppWinRT.cmake, Support/MidlRT.cmake, example/CMakeLists.txt, example/CommandLineWinRT/CMakeLists.txt, example/RuntimeComponent/CMakeLists.txt
This PR revisits the C++/WinRT integration to make it more idiomatically CMake-ish. The original implementation - `generate_winrt_projection` - was a simple function that would run the C++/WinRT tooling to make a projection during CMake generation. It was awkward to get details out of how to consume the projection (#30), it relied on implicit contract with the consumer (#18), and it didn't regenerate the projection when an input winmd would change (#31). To address these problems, I'm adding `add_cppwinrt_projection` which makes a couple of important changes:
1. It takes the name of a target to create, that the consumer can specify in `target_link_libraries`. By creating a target, the details of the projection are encapsulated away from the consumer. Include paths, libraries and settings …
=> Add 'add_cppwinrt_projection' for creating a C++/WinRT projection target

PowerShell.cmake, ToolchainCommon.cmake, VSWhere.cmake
Iterating on some simple cleanup:
1. ~~`toolchain_update_file` is equivalent to `file(GENERATE...`, switching over to have less code and to be more idiomatic.~~
2. `PowerShell.cmake` shouldn't always `find_program` for PowerShell; move the call into `execute_powershell`.
3. Move `getVSWhereProperty` into `findVisualStudio` to reduce the exposed surface area of `VSWhere.cmake`
In my self-hosting, item (1) was causing all sorts of breaks - I'm removing that commit until I understand it better.
=> Better encapsulation of implementation details

Windows.Kits.cmake, example/CMakePresets.json
`Windows.Kits.cmake` contains logic that it shouldn't choose a Windows SDK that is higher that the host OS version. That logic isn't sound, Windows SDK's are supported on older OS's, so removing the 'host OS' version check. I did notice that CMake has support for `CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION_MAXIMUM` ([documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION_MAXIMUM.html)) so added support to respect that variable to allow consumers to set a ceiling on SDK versions.
This addresses #34.
=> 'CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION' shouldn't be limited by host OS version

NuGet.cmake, VSWhere.cmake
As called out in #18 and #44, `VSWhere.cmake` and `NuGet.cmake` do work - including downloading files - when they're included, which is wasteful/noisy by default. This change moves the top-level logic into methods that do the necessary work, and adds a call to that method as needed, making the tooling download and initialization lazy.
=> 'VSWhere.cmake' and 'NuGet.cmake' should do no work by default

.cmake-format.yaml, .github/workflows/ci.yaml, NuGet.cmake, README.md, Support/CppWinRT.cmake, Support/MidlRT.cmake, VSWhere.cmake, analyze.ps1
This PR adds a '.cmake-format.yaml' file as suggested by @ClausKlein in #47. The rules enforce the style that was generally in use in the `.cmake` files in the repo and helped highlight places where things were inconsistent. I've added a simple `analyze.ps1` that runs `cmake-lint` across all files in the Git repo, and a Job to the existing CI Workflow that uses `analyze.ps1` to enforce the rules at CI- and PR- time.
=> Adding an initial '.cmake-format.yaml'

Tests/Ninja/Toolchain.Ninja.Tests.ps1, Tests/NuGet/Toolchain.NuGet.Tests.ps1
After running the Pester tests, the shell's location changes - the tests themselves change location, so the shell's location is left in the location of the last test that changed location. The tests should use BeforeAll/AfterAll to preserve and restore location.
=> Tests should preserve and restore Location

Support/Imports.cmake, example/CMakeLists.txt, example/CMakePresets.json, example/CommandLineImportLibrary/CMakeLists.txt, example/CommandLineImportLibrary/main.cpp
This is not-necessarily 'toolchain' related, but MSVC-related. There are cases where there's a need to build an import library from a list of exports - where an import library isn't shipped with a DLL, or where the imports aren't included in the import library for the DLL. The 'Imports.cmake' file adds `add_import_library` to generate a target representing an import library with the given exports.
=> Add 'add_import_library' for generating an import library from a list of exports

Windows.MSVC.toolchain.cmake
The origin regex which aimed to getting msvc version only worked when msvc displays English. That is, the regex matches the version after `Compiler Version`, It dosen't work when msvc displays other languages. For instance, in Chinese, msvc outputs `版本 <version>` instead of `Compiler Version <version>`.
I replace the regex based on the observation that the scanning always returns the path of cl.exe trailing with the msvc version.
=> Use a more generic regex to get msvc version

README.md
Thanks to @dg0yt for calling out that VCPkg respects [the `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` value](https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration#using-multiple-toolchain-files) for loading a nested toolchain from within the VCPkg toolchain. Updating the documentation to call this out.
=> Update VCPkg documentation with 'VCPKG_CHAINLOAD_TOOLCHAIN_FILE' details

Windows.MSVC.toolchain.cmake
The MSVC version number is not being properly parsed through the `cl.exe -Bv` command on my machine. The issue seems to be with the greedy regex pattern `.*` which matches the rest of the line eating up the version number. Changing this pattern to `[^0-9]*` seems to work fine.
=> Fix regex to get MSVC version

README.md, Windows.EWDK.toolchain.cmake, example/CMakeLists.txt, example/CMakePresets.json
As @kaloth called out in #74, using WindowsToolchain from an Enterprise WDK environment is a bit tricky. That review - I think - got the minimal fixes in to make it possible, this is a rough PR to get a better solution in place. There's work still to do:
Feedback on the code and above points is welcomed!
----
This PR adds the "Windows.EWDK.toolchain.cmake" file to make CMake builds with the EWDK easier - converting EWDK-initialized environment variables to CMake properties to then use "Windows.MSVC.toolchain.cmake"
=> Add a Windows.EWDK.toolchain.cmake

example/CMakePresets.json
When adding the `ewdk` preset, it was added above the `windows-msvc-x64`, which makes it the first non-hidden preset. For tooling that defaults to automatically configure the first non-hidden preset, having the `ewdk` preset first is a bit tricky, since it needs a specific environment. Moving `ewdk` further down the preset list puts `windows-msvc-x64` back as the default.
=> Move 'ewdk' lower in the presets list, so 'windows-msvc-x64' is the first non-hidden preset

Windows.MSVC.toolchain.cmake, example/CMakeLists.txt
#90 identified that the [`MSVC_TOOLSET_VERSION`](https://cmake.org/cmake/help/latest/variable/MSVC_TOOLSET_VERSION.html) isn't set when using the `Windows.EWDK.toolchain.cmake`. It turns out that it's not set when using the `Windows.MSVC.toolchain.cmake` either.
The toolchain files _do_ set [`MSVC_VERSION`](https://cmake.org/cmake/help/latest/variable/MSVC_VERSION.html), and that's the problem. By setting `MSVC_VERSION`, we end-up bypassing CMake's code to automatically set `MSVC_TOOLSET_VERSION` (and other variables) for us in [CMake/Modules/Platform/Windows-MSVC.cmake](https://github.com/Kitware/CMake/blob/bef9f0920f4f89d29e0c1138d377f19a0130f79a/Modules/Platform/Windows-MSVC.cmake#L48C1-L48C21). Removing the toolchain's code to calculate `MSVC_VERSION` seems like the right thing to do: …
=> Avoid setting MSVC_VERSION in the toolchain, rely on CMake setting it (and others)

VSWhere.cmake, Windows.MSVC.toolchain.cmake
`VS_USE_SPECTRE_MITIGATION_RUNTIME` instructs the toolchain to switch the library include path for the compiler runtime to a `spectre` sub-directory. When compiling with MSVC's ASAN support (i.e. `/fsanitize=address`) the compilation depends on `.lib` files that _aren't_ present in the `spectre` sub-directory, but _are_ present in the default library include path, breaking ASAN builds if `VS_USE_SPECTRE_MITIGATION_RUNTIME` is used. If `VS_USE_SPECTRE_MITIGATION_RUNTIME` were to _prefer_ the `spectre` subdirectory - rather than using it exclusively - then the ASAN libraries would still be found.
=> VS_USE_SPECTRE_MITIGATION_RUNTIME should prefer the Spectre library path, not use it exclusively

example/WindowsApplication/CMakeLists.txt, example/WindowsApplication/app.manifest
Add a manifest to 'example/WindowsApplication' to...
* ...show how to add desktop manifests to a CMake build
* ...mark the application as DPI-aware, so that the menus look better on a high-DPI monitor.
=> Add 'app.manifest' to example/WindowsApplication, mark as DPI aware

example/CMakePresets.json
The 'CMakePresets.json' file in the 'example' folder opts-in to functionality that requires opt-in features from Visual Studio:
1. `VS_USE_SPECTRE_MITIGATION_RUNTIME` - This uses the Spectre-mitigation runtimes by default, but Visual Studio doesn't install them by default.
2. `VS_EXPERIMENTAL_MODULE` - This adds the Visual Studio-shipped modules for C++ to the path, but Visual Studio doesn't install them by default.
Setting these options to `OFF` means that a default install of Visual Studio - with the C++ workload - should be able to build the examples.
=> Change example defaults to build by default

.github/workflows/ci.yaml, Windows.MSVC.toolchain.cmake, example/CMakePresets.json
[Discussion #93](https://github.com/MarkSchofield/WindowsToolchain/discussions/93) talks about the options of opt-ing-in-to and falling-back-from Spectre libraries. This PR changes behavior to *not* include the non-Spectre paths if Spectre libraries have been asked for.
=> Windows.MSVC.toolchain.cmake shouldn't fallback to non-Spectre folders on Spectre builds

Windows.Kits.cmake, Windows.MSVC.toolchain.cmake
On an ARM64 machine, Visual Studio installs 'host' compilers for arm64, x64 and x86. At the minute, WindowsToolchain defaults to the x64 'host' compilers, since it always defaults to x64 host compilers. But if WindowsToolchain prefers the arm64 host compilers, then there's a decent reduction in compilation and linking times. This PR changes WindowsToolchain to prefer the arm64 host compiler on an ARM64 machine. If consumers want a specific host compiler, the `CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE` variable can be set explicitly.
=> Prefer the 'arm64' host compiler on ARM64 hosts

README.md
As discussed in #101, the Pester tests were moved to [MarkSchofield/WindowsCMake](https://github.com/MarkSchofield/WindowsCMake), so there's no need to talk about Pester testing in the README.md
=> Remove references to Pester tests

.github/workflows/ci.yaml, example/CMakePresets.json
This change adds a ARM64 and X64 'Visual Studio 2022'-generator configurations. I'm hoping that they're useful in ensuring consistency between the 'Visual Studio 2022'-generator and the WindowsToolchain.
=> Add 'Visual Studio 2022' preset configurations

example/CMakePresets.json
It turns out that #107 was perhaps a bit rushed. Here's some fixes from trying out the presets:
1. _'windows-vs-*' preset should inherit from 'windows-vs'_ - I typo'd. The 'windows-vs-*' presets should've inherited from 'windows-vs' - just to follow the precedent I've set-up in `CMakePresets.json`. 'windows-vs' was just setting the generator as 'Visual Studio 17 2022', which - it turns out - is the default on Windows, so there's no functional difference here. But being explicit in the generator would be my preference, to make sure that folks don't accidentally pick-up a new one on CMake update.
2. _Set the windows-vs* target architecture using 'CMAKE_GENERATOR_PLATFORM', not 'CMAKE_SYSTEM_PROCESSOR'_ - The Visual Studio Generators expect `CMAKE_GENERATOR_PLATFORM` to set the target …
=> Fix a few problems in the windows-vs-* presets

example/CMakeLists.txt
[The CUDA documentation](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html) calls out that CUDA is only supported with native x64 compilers. Trying an ARM64 build fails. To that end, I'm scoping the 'example' build to only include the CUDA sample when `CMAKE_SYSTEM_PROCESSOR` is `AMD64`.
=> CUDA only supports x64 compilation; exclude the Cuda example from non-x64 builds

Windows.Clang.toolchain.cmake, Windows.MSVC.toolchain.cmake, example/CMakeLists.txt
#114 called out that toolset-related tooling can't be found in CMake using a common CMake idiom - `find_program` relying on `CMAKE_PROGRAM_PATH`. In the case of #114, it was `nmake`, but in investigating #115, it would also be useful in finding MASM - allowing the default CMake logic to find MASM without explicitly setting/managing, say, `CMAKE_ASM_MASM_COMPILER`. This PR adds two paths to `CMAKE_PROGRAM_PATH`:
1. The path to the host- and target- resolved path to the MSVC toolset tools.
This would allow CMake to find, say, nmake.exe, ml64.exe and armasm64.exe.
2. The path to the Windows SDK binaries.
This would allow CMake to find, say, mt.exe and signtool.exe.
There's an option to opt-out: setting `TOOLCHAIN_UPDATE_PROGRAM_PATH` to `OFF` will not update `CMAKE_PROGRAM_PATH`.
=> Include the VS toolset and Win32 SDK binary paths in the CMAKE_PROGRAM_PATH

example/CMakeLists.txt, example/CMakePresets.json, example/CommandLineAsm/CMakeLists.txt, example/CommandLineAsm/helper.AMD64.asm, example/CommandLineAsm/helper.ARM64.asm, example/CommandLineAsm/helper.X86.asm, example/CommandLineAsm/main.cpp
#117 fixed a bug in `ASM_MASM` usage - the Windows SDK's include paths should be added for the `ASM_MASM` language, so that `.asm` files can correctly find MASM `.inc` files that are shipped in the Windows SDK. This PR adds an 'example', so that it shows that things work, and makes sure that there's no regressions.
This change adds an 'example/CommandLineAsm' folder, with a simple example. A single function - `CallAsmCode` - is implemented in assembly. It takes no parameters, and returns the value `42`. And there's a 'main' that calls the function and prints out the value. I've added implementations for `ASM_MASM` (on X86 and AMD64), and I've added an example for `ASM_MARMASM`, which is used on ARM64. But the ARM64 example is a little broken. The ARM64 include files (for example …
=> Add an example that builds .asm files

.github/workflows/ci.yaml, Windows.Clang.toolchain.cmake, Windows.MSVC.toolchain.cmake
WindowsToolchain used to download Ninja if it was specified as the CMake Generator but wasn't present on the system. That functionality was moved to WindowsCMake (to give WindowsToolchain more focused responsibilities), but #99 called out that the functionality in WindowsCMake didn't consider the Visual Studio installed version of Ninja. The responsibility of the two projects - WindowsToolchain and WindowsCMake made reconciling things difficult; WindowsToolchain is intended to be scoped and minimally sufficient, and only perform 'toolchain'-responsibilities, WindowsCMake runs 'too late' in the CMake configuration to resolve the CMAKE_MAKE_PROGRAM. This PR proposes an alternative fix - WindowsToolchain can add the location of the "Visual Studio"-installed ninja to the …
=> Consider the Visual Studio path for Ninja

.github/workflows/ci.yaml, Windows.Clang.toolchain.cmake, Windows.EWDK.toolchain.cmake, Windows.MSVC.toolchain.cmake, example/CMakeLists.txt, example/CMakePresets.json
Fixes #123.
#105 discusses when `CMAKE_CROSSCOMPILING` should be set and cites the CMake documentation around `CMAKE_CROSSCOMPILING`. The crux - I think - comes down to [the logic in `Modules/CMakeDetermineSystem.cmake`](https://github.com/Kitware/CMake/blob/b346afce4fc977d875c613334ebb5365cd647453/Modules/CMakeDetermineSystem.cmake#L156C1-L182C8), where CMake sets `CMAKE_CROSSCOMPILING` itself, based on whether `CMAKE_SYSTEM_NAME` is set.
With this change, the toolchains no longer set `CMAKE_CROSSCOMPILING` at all and instead rely on the CMake logic. The toolchains will only set `CMAKE_SYSTEM_NAME` if `CMAKE_SYSTEM_PROCESSOR` is different to `CMAKE_SYSTEM_PROCESSOR`. And setting `CMAKE_SYSTEM_NAME` causes the CMake logic to configure `CMAKE_CROSSCOMPILING`. If `CMAKE_SYSTEM_NAME` _isn't_ …
=> CMAKE_CROSSCOMPILING should not be true, if the build targets the host processor

Windows.Clang.toolchain.cmake, Windows.MSVC.toolchain.cmake
Provide an option to opt-out of adding the VS redistributed ninja to the CMAKE_SYSTEM_PROGRAM_PATH.
=> Allow opt-ing out of adding the VS-redistributed ninja to the CMAKE_SYSTEM_PROGRAM_PATH
